import androidx.appcompat.app.AppCompatActivity
import com.example.crimecurber.DbHandler
import android.location.LocationManager
import android.os.Bundle
import com.example.crimecurber.R
import com.example.crimecurber.FetchContacts
import android.widget.Toast
import androidx.core.app.ActivityCompat
import android.content.pm.PackageManager
import androidx.core.content.ContextCompat
import com.example.crimecurber.PermissionUtils
import com.example.crimecurber.Emergency
import android.widget.EditText
import android.content.Intent
import android.content.DialogInterface
import android.database.sqlite.SQLiteOpenHelper
import android.database.sqlite.SQLiteDatabase
import android.content.ContentValues
import android.widget.ArrayAdapter
import com.example.crimecurber.PermissionUtils.RationaleDialog
import com.example.crimecurber.PermissionUtils.PermissionDeniedDialog
import com.google.firebase.storage.StorageReference
import com.google.firebase.database.DatabaseReference
import android.app.ProgressDialog
import com.google.firebase.storage.FirebaseStorage
import com.google.firebase.database.FirebaseDatabase
import android.app.Activity
import android.content.ContentResolver
import android.webkit.MimeTypeMap
import com.google.android.gms.tasks.OnSuccessListener
import com.example.crimecurber.uploadinfo
import com.google.android.gms.tasks.OnFailureListener
import com.google.firebase.storage.OnProgressListener